name: "Last non-merge commit"
description: "Get the last non-merge commit"
inputs:
  checkout:
    name: Checkout
    description: "Run checkout action (if false, checkout should be called in previous step with fetch-depth: 0)"
    required: true
    default: true
outputs:
  value:
    description: "The last non-merge commit"
    value: ${{ steps.calculation.outputs.value }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v5
      if: ${{ inputs.checkout == 'true' }}
      with:
        fetch-depth: 0
        ref: ${{ github.sha }}
    - name: Set last non-merge commit
      id: calculation
      run: |
        # Execute your command and capture its output (e.g., using a variable)
        value=$(git rev-list --no-merges -n 1 HEAD)
        echo "Last non-merge commit: $value"
        echo "value=$value" >> $GITHUB_OUTPUT
      shell: bash